apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: behealthy
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
      - name: gcp-keyfile
        secret:
          secretName: gcp-keyfile
          optional: false 
      containers:
      - name: frontend
        image: amserdion/behealthyfe:main
        volumeMounts:
        - name: gcp-keyfile
          mountPath: /etc/secrets
          readOnly: true
        env:
          - name: DATABASE_URL
            value: postgres://postgres:postgrespw@postgres.behealthy.svc.cluster.local:5433/postgres?sslmode=disable #todo
          - name: NEXTAUTH_SECRET
            value: 9546e6e3665750a61ed3da81295509b4
          - name: NEXTAUTH_URL
            value: http://localhost:3000
          - name: GOOGLE_CLIENT_ID
            value: 425291061241-thulhehn4rhu1chqa9n8o9fdbfq8nkqr.apps.googleusercontent.com
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
                secretKeyRef:
                  name: secrets
                  key: client_secret
          - name: NEXT_PUBLIC_API_URL
            value: http://localhost:8888/v1/recipe
          - name: API_URL
            value: http://localhost:8888/v1/recipe
          - name: DISCORD_CLIENT_ID
            value: 425291061241-thulhehn4rhu1chqa9n8o9fdbfq8nkqr.apps.googleusercontent.com
          - name: DISCORD_CLIENT_SECRET
            value: 425291061241-thulhehn4rhu1chqa9n8o9fdbfq8nkqr.apps.googleusercontent.com
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"