apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: behealthy
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: amserdion/behealthybe:main
        env:
          - name: DSN
            valueFrom:
              secretKeyRef:
                name: url
                key: DSN
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"