apiVersion: v1
kind: Secret
metadata:
  name: url
type: Opaque
data:
  DSN: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc3B3QHBvc3RncmVzLmJlaGVhbHRoeS5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL3Bvc3RncmVzP3NzbG1vZGU9ZGlzYWJsZQ==
