apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: behealthy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: amserdion/behealthydb
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        
            